pawsitive/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: [] do
    get :profile, on: :collection
  end

  resources :bookings, only: [:new, :create, :show, :edit, :index] do
    post 'create_message', on: :member
    patch 'update_status', on: :member
    resources :messages, only: [:show]
  end

  resources :services, only: [:index, :show, :new, :create]


  resources :services, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create, :edit]
  end

  resources :notifications, only: [:index, :show] do
    collection do
      get :unread_count
    end

    member do
      patch :mark_as_read
    end
  end

  get 'home/index'
  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"
end

pawsitive/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    current_params = filters_params unless params[:filters].nil?
    lat, long = coordinates current_params
    @services = Service.filtered current_params, lat, long
    @locations = @services.map {|s| { latitude: s.member.latitude, longitude: s.member.longitude, tooltip: s.member.display_name, label: "$#{s.price["small_dog"]}" } } 
    @locations = [{latitude: lat, longitude: long}] if @locations.empty?
    @zip = current_user&.zip || "94041"
  end

  private

  def filters_params
    params.require(:filters).permit(:service_type, :location, :pet_number, dates: [:start, :end], pet_types: [:dog, :cat],
      dog_size: [:s, :m, :l, :xl], price: [:min, :max], filters: [
        housing_conditions: [:has_house, :has_fence, :furniture_allowed, :bed_allowed, :no_smoking],
        pets_in_home: [:no_dog, :no_cat, :one_at_a_time, :no_caged_pets],
        children_in_home: [:none, :none_0_to_5, :none_6_to_12],
        additional_services: [:puppy_care, :cat_care, :accepts_unspayed_females, :accepts_non_neutered_male, :bathing_grooming, :first_aid]
      ])
  end

  def coordinates(current_params)
    if current_params && current_params[:location] && current_params[:location] != (current_user&.zip || "94041")
      location_to_lat_long(current_params[:location])
    else
      [current_user&.latitude || 37.3897, current_user&.longitude || -122.0832] 
    end
  end

  def location_to_lat_long(zip)
    puts "Calling GeoCode API..."
    location = Net::HTTP.get(URI("https://api.mapbox.com/search/geocode/v6/forward?q=#{zip}&access_token=#{ENV["MAPBOX_ACCESS_TOKEN"]}"))
    res = JSON.parse(location)
    lat_long = res["features"].first["properties"]["coordinates"]
    [lat_long["latitude"], lat_long["longitude"]]
  end
end

pawsitive/app/helpers/home_helper.rb
module HomeHelper
end

pawsitive/app/views/home/_filters.html.erb
<%= form_with scope: "filters", method: :get, data: { turbo_frame: "services" } do |f| %>
  <div class="bg-white px-4 leading-8" data-controller="filters">
    <fieldset class="mb-4">
      <%= f.label :service_type, class: "block" %>
      <%= f.select :service_type, ["Boarding", "Day Care","Sitting"], {}, class: "w-full", onchange: "this.form.requestSubmit()" %>
    </fieldset>
    <fieldset class="my-4">
      <%= f.label :location, "Near", class: "block" %>
      <%= f.text_field :location, placeholder: "Zip code or Address", value: @zip, class: "w-full" %>
    </fieldset>
    <fieldset class="my-4">
      <p>Dates</p>
      <div class="flex w-full">
        <%= f.fields_for :dates do |dates| %>
          <%= dates.text_field :start, class: "w-[50%] md:w-32", placeholder: "Drop off", onfocus: "this.type='date';this.showPicker();", onblur: "this.type='text'", onchange: "this.form.requestSubmit()" %>
          <svg class="inline w-4 mx-1 fill-slate-400" viewBox="0 0 32 32"><path d="M26.793 17H3a1 1 0 110-2h23.793L21.5 9.707a1 1 0 011.414-1.414l6.647 6.646a1.5 1.5 0 010 2.122l-6.647 6.646a1 1 0 01-1.414-1.414L26.793 17z"></path></svg>
          <%= dates.text_field :end, class: "w-[50%] md:w-32", placeholder: "Pick up", onfocus: "this.type='date';this.showPicker();", onblur: "this.type='text'", onchange: "this.form.requestSubmit()" %>
        <% end %>
      </div>
    </fieldset>
    <div class="md:hidden py-4 mb-1" data-filters-target="hidable">
      <button class="btn-primary ms-auto me-auto" data-action="click->filters#toggle">More filters</button>
    </div>
    <div class="toggle hidden md:block" data-filters-target="hidable">
      <fieldset class="my-4">
        <p>How many pets?</p>
        <div class="flex justify-around">
          <div>
            <%= f.label :pet_number_1, "1" %>
            <%= f.radio_button :pet_number, "1", onchange: "this.form.requestSubmit()" %>
          </div>
          <div>
            <%= f.label :pet_number_2, "2" %>
            <%= f.radio_button :pet_number, "2", onchange: "this.form.requestSubmit()" %>
          </div>
          <div>
            <%= f.label :pet_number_3, "3+" %>
            <%= f.radio_button :pet_number, "3+", onchange: "this.form.requestSubmit()" %>
          </div>
        </div>
      </fieldset>
      <fieldset class="my-4">
        <p>Pet type(s)</p>
        <div class="flex justify-around">
          <%= f.fields_for :pet_types do |pet_types| %>
            <div>
              <%= pet_types.label :dog, "Dog" %>
              <%= pet_types.check_box :dog, checked: true, onchange: "this.form.requestSubmit()" %>
            </div>
            <div>
              <%= pet_types.label :cat, "Cat" %>
              <%= pet_types.check_box :cat, onchange: "this.form.requestSubmit()" %>
            </div>
          <% end %>
        </div>
      </fieldset>
      <%# if pet_type_cat && !pet_cat_dog %>
      <fieldset class="my-4">
        <p>Dog size (lbs)</p>
        <div class="flex justify-between content-center">
          <%= f.fields_for :dog_size do |dog_size| %>
            <div>
              <%= dog_size.label :s, "0-15" %>
              <%= dog_size.check_box :s, onchange: "this.form.requestSubmit()" %>
            </div>
            <div>
              <%= dog_size.label :m, "16-40" %>
              <%= dog_size.check_box :m, onchange: "this.form.requestSubmit()" %>
            </div>
            <div>
              <%= dog_size.label :l, "41-100" %>
              <%= dog_size.check_box :l, onchange: "this.form.requestSubmit()" %>
            </div>
            <div>
              <%= dog_size.label :xl, "100+" %>
              <%= dog_size.check_box :xl, onchange: "this.form.requestSubmit()" %>
            </div>
          <% end %>
        </div>
      </fieldset>
      <fieldset class="my-4 pb-1">
        <%= f.fields_for :price do |price| %>
          <p class="block mb-2">Rate per day/night</p>
          <div class="flex content-center">
            <span class="basis-10" id="fromInput">$1</span>
            <%= price.hidden_field :min, value: 1 %>
            <div class="sliders_control relative min-h-50px flex-1 flex items-center">
              <input id="fromSlider" type="range" value="1" min="1" max="250" class="range-slider-inputs h-0 z-10"/>
              <input id="toSlider" type="range" value="250" min="1" max="250" class="range-slider-inputs h-1.5 rounded-md"/>
            </div>
            <span class="basis-10" id="toInput">$250</span>
            <%= price.hidden_field :max, value: 250 %>
          </div>
        <% end %>
      </fieldset>
      <%= render partial: "filters_details", locals: {f: f} %>
    </div>
  </div>
<% end %>

pawsitive/app/views/home/_filters_details.html.erb
<div class="px-4 mt-4 pt-4 pb-2 leading-9 bg-slate-200 -mx-4">
  <%= f.fields_for :filters do |filters| %>
    <div class="flex justify-between">
      <span>Filters</span>
      <button type="reset" class="text-blue-700 font-semibold" data-controller="slider" data-action="click->slider#reset">Reset all</button>
    </div>
    <fieldset class="my-4">
      <%= filters.fields_for :housing_conditions do |housing_conditions| %>
      <legend class="font-semibold">Housing Conditions</legend>
      <div class="w-full border-t border-slate-500 h-2"></div>
        <div>
          <%= housing_conditions.check_box :has_house, onchange: "this.form.requestSubmit()" %>
          <%= housing_conditions.label :has_house, "Has house (excludes apartments)" %>
        </div>
        <div>
          <%= housing_conditions.check_box :has_fence, onchange: "this.form.requestSubmit()" %>
          <%= housing_conditions.label :has_fence, "Has fenced yard" %>
        </div>
        <div>
          <%= housing_conditions.check_box :furniture_allowed, onchange: "this.form.requestSubmit()" %>
          <%= housing_conditions.label :furniture_allowed, "Dogs allowed on furniture" %>
        </div>
        <div>
          <%= housing_conditions.check_box :bed_allowed, onchange: "this.form.requestSubmit()" %>
          <%= housing_conditions.label :bed_allowed, "Dogs allowed on bed" %>
        </div>
        <div>
          <%= housing_conditions.check_box :no_smoking, onchange: "this.form.requestSubmit()" %>
          <%= housing_conditions.label :no_smoking, "Non-smoking home" %>
        </div>
      <% end %>
    </fieldset>
    <fieldset class="my-4">
      <%= filters.fields_for :pets_in_home do |pets_in_home| %>
        <legend class="font-semibold">Pets in the home</legend>
        <div class="w-full border-t border-slate-500 h-2"></div>
        <div>
          <%= pets_in_home.check_box :no_dog, onchange: "this.form.requestSubmit()" %>
          <%= pets_in_home.label :no_dog, "Doesn't own a dog" %>
        </div>
        <div>
          <%= pets_in_home.check_box :no_cat, onchange: "this.form.requestSubmit()" %>
          <%= pets_in_home.label :no_cat, "Doesn't own a cat" %>
        </div>
        <div>
          <%= pets_in_home.check_box :one_at_a_time, onchange: "this.form.requestSubmit()" %>
          <%= pets_in_home.label :one_at_a_time, "Accepts only one client at a time" %>
        </div>
        <div>
          <%= pets_in_home.check_box :no_caged_pets, onchange: "this.form.requestSubmit()" %>
          <%= pets_in_home.label :no_caged_pets, "Does not own caged pets" %>
        </div>
      <% end %>
    </fieldset>
    <fieldset class="my-4">
      <%= filters.fields_for :children_in_home do |children_in_home| %>
        <legend class="font-semibold">Children in the home</legend>
        <div class="w-full border-t border-slate-500 h-2"></div>
        <div>
          <%= children_in_home.check_box :none, onchange: "this.form.requestSubmit()" %>
          <%= children_in_home.label :none, "Has no children" %>
        </div>
        <div>
          <%= children_in_home.check_box :none_0_to_5, onchange: "this.form.requestSubmit()" %>
          <%= children_in_home.label :none_0_to_5, "No children 0-5 years old" %>
        </div>
        <div>
          <%= children_in_home.check_box :none_6_to_12, onchange: "this.form.requestSubmit()" %>
          <%= children_in_home.label :none_6_to_12, "No children 6-12 years old" %>
        </div>
      <% end %>
    </fieldset>
    <fieldset class="my-4">
      <%= filters.fields_for :additional_services do |additional_services| %>
        <legend class="font-semibold">Additional services</legend>
        <div class="w-full border-t border-slate-500 h-2"></div>
        <div>
          <%= additional_services.check_box :puppy_care, onchange: "this.form.requestSubmit()" %>
          <%= additional_services.label :puppy_care, "Puppy care" %>
        </div>
        <div>
          <%= additional_services.check_box :cat_care, onchange: "this.form.requestSubmit()" %>
          <%= additional_services.label :cat_care, "Cat care" %>
        </div>
        <div>
          <%= additional_services.check_box :accepts_unspayed_females, onchange: "this.form.requestSubmit()" %>
          <%= additional_services.label :accepts_unspayed_females, "Accepts unspayed female dogs" %>
        </div>
        <div>
          <%= additional_services.check_box :accepts_non_neutered_male, onchange: "this.form.requestSubmit()" %>
          <%= additional_services.label :accepts_non_neutered_male, "Accepts non neutered male dogs" %>
        </div>
        <div>
          <%= additional_services.check_box :bathing_grooming, onchange: "this.form.requestSubmit()" %>
          <%= additional_services.label :bathing_grooming, "Bathing / Grooming" %>
        </div>
        <div>
          <%= additional_services.check_box :first_aid, onchange: "this.form.requestSubmit()" %>
          <%= additional_services.label :first_aid, "Dog first-aid / CPR" %>
        </div>
      <% end %>
    </fieldset>
  <% end %>
  <button class="block sm:hidden btn-primary ms-auto me-auto" data-action="click->filters#toggle">Less filters</button>
</div>

pawsitive/app/views/home/_footer.html.erb
<div class="px-4 pt-16 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8">
  <div class="grid gap-10 row-gap-6 mb-8 sm:grid-cols-2 lg:grid-cols-4">
    <div class="sm:col-span-2">
      <a href="/" aria-label="Go home" title="Company" class="inline-flex items-center">
        <svg class="w-8 text-deep-purple-accent-400" viewBox="0 0 24 24" stroke-linejoin="round" stroke-width="2" stroke-linecap="round" stroke-miterlimit="10" stroke="currentColor" fill="none">
          <rect x="3" y="1" width="7" height="12"></rect>
          <rect x="3" y="17" width="7" height="6"></rect>
          <rect x="14" y="1" width="7" height="6"></rect>
          <rect x="14" y="11" width="7" height="12"></rect>
        </svg>
        <span class="ml-2 text-xl font-bold tracking-wide text-gray-800 uppercase">Pawsitive</span>
      </a>
      <div class="mt-6 lg:max-w-sm">
        <p class="text-sm text-gray-800">
          Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.
        </p>
        <p class="mt-4 text-sm text-gray-800">
          Eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
        </p>
      </div>
    </div>
    <div class="space-y-2 text-sm">
      <p class="text-base font-bold tracking-wide text-gray-900">Contacts</p>
      <div class="flex">
        <p class="mr-1 text-gray-800">Phone:</p>
        <a href="tel:850-123-5021" aria-label="Our phone" title="Our phone" class="transition-colors duration-300 text-deep-purple-accent-400 hover:text-deep-purple-800">850-123-5021</a>
      </div>
      <div class="flex">
        <p class="mr-1 text-gray-800">Email:</p>
        <a href="mailto:info@lorem.mail" aria-label="Our email" title="Our email" class="transition-colors duration-300 text-deep-purple-accent-400 hover:text-deep-purple-800">info@lorem.mail</a>
      </div>
      <div class="flex">
        <p class="mr-1 text-gray-800">Address:</p>
        <a href="https://www.google.com/maps" target="_blank" rel="noopener noreferrer" aria-label="Our address" title="Our address" class="transition-colors duration-300 text-deep-purple-accent-400 hover:text-deep-purple-800">
          312 Lovely Street, NY
        </a>
      </div>
    </div>
    <div>
      <span class="text-base font-bold tracking-wide text-gray-900">Social</span>
      <div class="flex items-center mt-1 space-x-3">
        <a href="/" class="text-gray-500 transition-colors duration-300 hover:text-deep-purple-accent-400">
          <svg viewBox="0 0 24 24" fill="currentColor" class="h-5">
            <path
              d="M24,4.6c-0.9,0.4-1.8,0.7-2.8,0.8c1-0.6,1.8-1.6,2.2-2.7c-1,0.6-2,1-3.1,1.2c-0.9-1-2.2-1.6-3.6-1.6 c-2.7,0-4.9,2.2-4.9,4.9c0,0.4,0,0.8,0.1,1.1C7.7,8.1,4.1,6.1,1.7,3.1C1.2,3.9,1,4.7,1,5.6c0,1.7,0.9,3.2,2.2,4.1 C2.4,9.7,1.6,9.5,1,9.1c0,0,0,0,0,0.1c0,2.4,1.7,4.4,3.9,4.8c-0.4,0.1-0.8,0.2-1.3,0.2c-0.3,0-0.6,0-0.9-0.1c0.6,2,2.4,3.4,4.6,3.4 c-1.7,1.3-3.8,2.1-6.1,2.1c-0.4,0-0.8,0-1.2-0.1c2.2,1.4,4.8,2.2,7.5,2.2c9.1,0,14-7.5,14-14c0-0.2,0-0.4,0-0.6 C22.5,6.4,23.3,5.5,24,4.6z"
            ></path>
          </svg>
        </a>
        <a href="/" class="text-gray-500 transition-colors duration-300 hover:text-deep-purple-accent-400">
          <svg viewBox="0 0 30 30" fill="currentColor" class="h-6">
            <circle cx="15" cy="15" r="4"></circle>
            <path
              d="M19.999,3h-10C6.14,3,3,6.141,3,10.001v10C3,23.86,6.141,27,10.001,27h10C23.86,27,27,23.859,27,19.999v-10   C27,6.14,23.859,3,19.999,3z M15,21c-3.309,0-6-2.691-6-6s2.691-6,6-6s6,2.691,6,6S18.309,21,15,21z M22,9c-0.552,0-1-0.448-1-1   c0-0.552,0.448-1,1-1s1,0.448,1,1C23,8.552,22.552,9,22,9z"
            ></path>
          </svg>
        </a>
        <a href="/" class="text-gray-500 transition-colors duration-300 hover:text-deep-purple-accent-400">
          <svg viewBox="0 0 24 24" fill="currentColor" class="h-5">
            <path
              d="M22,0H2C0.895,0,0,0.895,0,2v20c0,1.105,0.895,2,2,2h11v-9h-3v-4h3V8.413c0-3.1,1.893-4.788,4.659-4.788 c1.325,0,2.463,0.099,2.795,0.143v3.24l-1.918,0.001c-1.504,0-1.795,0.715-1.795,1.763V11h4.44l-1,4h-3.44v9H22c1.105,0,2-0.895,2-2 V2C24,0.895,23.105,0,22,0z"
            ></path>
          </svg>
        </a>
      </div>
      <p class="mt-4 text-sm text-gray-500">
        Bacon ipsum dolor amet short ribs pig sausage prosciutto chicken spare ribs salami.
      </p>
    </div>
  </div>
  <div class="flex flex-col-reverse justify-between pt-5 pb-10 border-t lg:flex-row">
    <p class="text-sm text-gray-600">
      © Copyright 2024 Pawsitive Inc. All rights reserved.
    </p>
    <ul class="flex flex-col mb-3 space-y-2 lg:mb-0 sm:space-y-0 sm:space-x-5 sm:flex-row">
      <li>
        <a href="/" class="text-sm text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">F.A.Q</a>
      </li>
      <li>
        <a href="/" class="text-sm text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">Privacy Policy</a>
      </li>
      <li>
        <a href="/" class="text-sm text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">Terms &amp; Conditions</a>
      </li>
    </ul>
  </div>
</div>

pawsitive/app/views/home/_navbar.html.erb
<div class="top-0 py-1 lg:py-2 w-full bg-transparent z-50 dark:bg-gray-900 relative" >
  <nav class="z-10 sticky top-0 left-0 right-0 max-w-4xl xl:max-w-5xl mx-auto px-5 py-2.5 lg:border-none lg:py-4" data-controller="navbar">
    <div class="flex items-center justify-center lg:justify-between">
      <div class="flex items-center space-x-2">
        <%= link_to "Pawsitive", root_path, class: "text-black dark:text-white font-bold text-2xl" %>
      </div>
      <div class="absolute bg-white top-full right-0 left-0 h-lvh pt-8 scale-x-0 lg:static lg:h-auto lg:pt-0 lg:bg-transparent lg:scale-x-100 transition-transform duration-500 origin-right" data-navbar-target="menu">
        <div class="flex items-center gap-6 flex-col lg:flex-row lg:gap-x-2">
          <% if user_signed_in? %>
            <%= link_to "Profile",profile_users_path(current_user.id), class: "btn-primary"%>
            <%= button_to "Logout", destroy_user_session_path, class: "btn-primary", method: :delete %>
            <p class="text-black lg:text-white"><%= current_user.email %></p>
            <div class="nav-item ms-1" id="notifications">
              <%= link_to notifications_path, class: 'nav-link' do %>
                <i class="fa-regular fa-bell font-bold text-2xl text-black lg:text-white"></i>
                <% if @unread_notifications_count.to_i > 0 %>
                <span id="notification-count" class="inline-flex items-center bg-red-500 rounded-md px-2 py-1 text-xs font-medium text-white ring-1 ring-inset ring-red-600/10 h-[14px] absolute" data-notification-target="count">
                  <%= @unread_notifications_count if @unread_notifications_count.to_i > 0 %>
                </span>
                <% end %>
              <% end %>
            </div>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, class: "btn-secondary text-black lg:text-white" %>
            <%= link_to "Login", new_user_session_path, class: "btn-primary" %>
          <% end %>
        </div>
      </div>
      <div class="flex items-center justify-center absolute right-4 lg:hidden">
        <button class="focus:outline-none text-slate-200 dark:text-white " data-action="navbar#toggle">
          <svg
            stroke="currentColor"
            fill="currentColor"
            stroke-width="0"
            viewBox="0 0 20 20"
            aria-hidden="true"
            class="text-2xl text-slate-800 dark:text-white focus:outline-none active:scale-110 active:text-red-500"
            height="1em"
            width="1em"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fill-rule="evenodd"
              d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM9 15a1 1 0 011-1h6a1 1 0 110 2h-6a1 1 0 01-1-1z"
              clip-rule="evenodd"
            ></path>
          </svg>
        </button>
      </div>
    </div>
  </nav>
</div>

pawsitive/app/views/home/_service_card.html.erb
<%= link_to service_path(service.id), target: :_blank do %>
  <div class="py-4 px-4 border-b border-l-4 border-l-transparent hover:border-l-blue-600">
    <div class="flex justify-between items-center">
      <div class="flex items-center">
        <div class="w-8 md:w-24 aspect-square overflow-hidden rounded-full">
          <%= image_tag(service.member.avatar, class: "aspect-square h-full w-full") %>
        </div>
        <div class="mx-4">
          <h2 class="text-2xl font-semibold"><%= service.member.display_name %></h2>
          <p class="truncate max-w-[18ch] md:max-w-[30ch]"><%= service.member.bio %></p>
          <p><%= service.member.city %></p>
        </div>
      </div>
      <div class="text-right">
        <p>from</p>
        <p class="text-blue-700 text-2xl font-bold">$<%= service.price["small_dog"] %></p>
        <p>per night</p>
      </div>
    </div>
    <p class="my-4"><%= service.description %></p>
  </div>
<% end %>

pawsitive/app/views/home/index.html.erb
<div class="flex flex-1 bg-slate-200 pt-1 flex-col md:flex-row">
  <section class="basis-20 shrink-0 px-1">
    <%= render partial: "filters" %>
  </section>
  <%= turbo_frame_tag "services", class: "flex flex-1" do %>
    <section class="bg-white flex-[4]">
      <div id="services" class="w-full">
        <% if @services.empty? %>
          <div class="px-8 ms-auto me-auto pt-16 grid text-center">
            <p class="font-semibold text-xl mb-8">We couldn't find any sitters that matched your criteria.</p>
            <p>Try changing your search criteria or updating your location.</p>
          </div>
        <% else %>
          <% @services.each_with_index do |service, i| %>
            <%= render partial: "service_card", locals: {service: service, index: i + 1} %>
          <% end %>
        <% end %>
      </div>
    </section>
    <section class="flex-[3] px-1 hidden md:block">
        <%= js_map @locations, id: "cities-map", height: "100%"%>
    </section> 
  <% end %>
</div>