pawsitive/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: [] do
    get :profile, on: :collection
  end

  resources :bookings, only: [:new, :create, :show, :edit, :index] do
    post 'create_message', on: :member
    patch 'update_status', on: :member
    resources :messages, only: [:show]
  end

  resources :services, only: [:index, :show, :new, :create]


  resources :services, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create, :edit]
  end

  resources :notifications, only: [:index, :show] do
    collection do
      get :unread_count
    end

    member do
      patch :mark_as_read
    end
  end

  get 'home/index'
  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"
end

pawsitive/app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notifiable, polymorphic: true

  scope :unread, -> { where(read: false) }
end

pawsitive/app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_notification, only: [:show, :mark_as_read]

  def index
    @notifications = current_user.notifications.order(created_at: :desc)
  end

  def show
    if @notification.notifiable_type == 'Message'
      @message = @notification.notifiable
      @booking = @message.booking
    elsif @notification.notifiable_type == 'Booking'
      @booking = @notification.notifiable
      @messages = @booking.messages
    end
  end

  def mark_as_read
    @notification.update(read: true)
    redirect_to notifications_path, notice: 'Notification marked as read.'
  end

  def unread_count
    count = current_user.notifications.unread.count
    render json: { count: count }
  end

  private

  def set_notification
    @notification = current_user.notifications.find(params[:id])
  end
end

pawsitive/app/helpers/notifications_helper.rb
module NotificationsHelper
end

pawsitive/app/views/notifications/index.html.erb
<section class="flex flex-col justify-normal items-center min-h-screen p-4 bg-gray-50">
  <h1 class="text-2xl font-bold my-4 text-center">Notifications</h1>
  <p class="text-gray-500 mb-4 text-center">You have <span id="unread-notification-count"><%= @unread_notifications_count %></span> unread notifications</p>
  <ul role="list" class="divide-y divide-gray-100 w-full max-w-2xl">
    <% @notifications.each do |notification| %>
      <li class="flex flex-col sm:flex-row justify-between gap-x-6 py-5 border rounded-xl px-3 bg-white shadow-sm">
        <div class="flex items-center gap-x-4">
          <% if notification.notifiable.sender.avatar.attached? %>
            <%= image_tag(notification.notifiable.sender.avatar, class: "h-12 w-12 flex-none rounded-full bg-gray-50", alt: 'avatar') %>
          <% end %>
          <div class="min-w-0 flex-auto">
            <% if notification.notifiable_type == 'Message' %>
              <p class="text-sm font-semibold leading-6 text-gray-900">
                <%= link_to "New message from #{notification.notifiable.sender.first_name}", booking_message_path(notification.notifiable.booking, notification.notifiable), 
                  class: "text-blue-500 hover:underline", data: { action: "click->notification#markAsRead", notification_id: notification.id } %>
              </p>
              <p class="mt-1 truncate text-xs leading-5 text-gray-500">
                <%= notification.notifiable.sender.email %>
              </p>
            <% elsif notification.notifiable_type == 'Booking' %>
              <p class="text-sm font-semibold leading-6 text-gray-900">
                <%= link_to "New booking from #{notification.notifiable.user.first_name}", booking_path(notification.notifiable), class: "text-green-500 hover:underline", 
                  data: { action: "click->notification#markAsRead", notification_id: notification.id } %>
              </p>
              <p class="mt-1 truncate text-xs leading-5 text-gray-500">
                Service: <%= notification.notifiable.service.service_type %>
              </p>
            <% end %>
          </div>
        </div>
        <div class="mt-4 sm:mt-0 sm:ml-4 flex sm:flex-col sm:items-end">
          <%= form_with url: mark_as_read_notification_path(notification), method: :patch, local: true, data: { action: "ajax:success->notification#updateUnreadCount" } do %>
            <%= hidden_field_tag :_method, 'patch' %>
            <%= submit_tag 'Mark as read', class: "text-sm text-gray-500 hover:text-gray-700 hover:cursor-pointer transition duration-300" %>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
</section>